theme: minima
title: My first blog ! 
author: JulisMaximus80
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blog for data lovers *en español y english*


# social links
twitter_username: JuliusEC # DO NOT include the @ character, or else the build will fail!
github_username:  JuliusMaximus80 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
